[project]
name = "interactions-google"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "fastapi[standard]>=0.124.4",
    "numpy>=2.3.5",
    "python-multipart>=0.0.20",
    "uvicorn>=0.38.0",
]
